---VI--SAN PHAM KHOA HOC VÀ CONG NGHE
---SANPHAMTHUCTE
CREATE PROC dbo.proc_PrintBCDK_VI_SANPHAMTHUCTE
	@BCKQID INT
AS
SELECT *,CONVERT(nvarchar(20),ThoiGian,103) pThoiGian
 FROM SANPHAMTHUCTE NOLOCK WHERE BaoCaoKetQuaID=@BCKQID
GO