CREATE TABLE [dbo].[HOINGHI_LAPCHUONGTRINH_CHITIET]
(
	[LapChuongTrinhChiTietID] INT NOT NULL IDENTITY, 
    [DiaDiem] NVARCHAR(1000) NULL, 
	[ThoiGianTu] DATETIME NULL,
	[ThoiGianDen] DATETIME NULL,
	[ChuToa] NVARCHAR(1000) NULL,
	[Phien] NVARCHAR(1000) NULL,
	[STT] INT NULL,
    [NoiDung] NVARCHAR(1000) NULL,
	[BaoCaoVien] NVARCHAR(1000) NULL,
	[DMKhoiID] INT NULL,
	[GhiChu] NVARCHAR(1000) NULL,
	LapChuongTrinhID INT, 
	CONSTRAINT PK_HOINGHI_LAPCHUONGTRINH_CHITIET_LapChuongTrinhChiTietID PRIMARY KEY  CLUSTERED (LapChuongTrinhChiTietID ASC),
    CONSTRAINT [FK_HOINGHI_LAPCHUONGTRINH_CHITIET_HOINGHI_LAPCHUONGTRINH] FOREIGN KEY (LapChuongTrinhID) REFERENCES HOINGHI_LAPCHUONGTRINH(LapChuongTrinhID), 
    CONSTRAINT [FK_HOINGHI_LAPCHUONGTRINH_CHITIET_DANHMUC_KHOI] FOREIGN KEY (DMKhoiID) REFERENCES DANHMUC_KHOI(DMKhoiID)
)
