CREATE TABLE [dbo].[HOINGHI_TOCHUCMODOT]
(
	 HoiNghiID INT NOT NULL IDENTITY 
	,MaHoiNGhi NVARCHAR(1000)
	,TenHoiNghi NVARCHAR(1000)
	,ThoiGianTu DATETIME
	,ThoiGianDen DATETIME
	,UserID int NULL
	,TrangThaiHoiNghi INT NULL--ENUM
	,CONSTRAINT PK_HOINGHI_TOCHUCMODOT_HoiNghiID PRIMARY KEY  CLUSTERED (HoiNghiID ASC)
)

GO

