CREATE TABLE [dbo].[HOINGHI_LAPCHUONGTRINH]
(
	LapChuongTrinhID INT NOT NULL IDENTITY 
	,HoiNghiID  INT
	,ChiTiet NVARCHAR(1000)
	,GhiChu NVARCHAR(1000)
	,[Ngay] DATE NULL, 
    CONSTRAINT PK_HOINGHI_LAPCHUONGTRINH_LapChuongTrinhID PRIMARY KEY  CLUSTERED (LapChuongTrinhID ASC)
	,CONSTRAINT [FK_HOINGHI_LAPCHUONGTRINH_HOINGHI_DANGKY] FOREIGN KEY (HoiNghiID) REFERENCES HOINGHI_TOCHUCMODOT(HoiNghiID) 
)

GO

CREATE NONCLUSTERED INDEX [IX_HOINGHI_LAPCHUONGTRINH_HoiNghiID] ON [dbo].[HOINGHI_LAPCHUONGTRINH] (HoiNghiID ASC)
