CREATE TABLE [dbo].[HOINGHI_GUIBAIDANGKY]
(
	GuiBaiDangKyID INT NOT NULL IDENTITY 
   ,NguoiNhan NVARCHAR(1000) NULL
   ,DMKhoaPhongID INT NULL
   ,Email NVARCHAR(1000)
   ,SoDT NVARCHAR(1000)
   ,NgayGui Date
   ,HoiNghiID INT NULL
   ,CONSTRAINT PK_HOINGHI_GUIBAIDANGKY_GuiBaiDangKyID PRIMARY KEY  CLUSTERED (GuiBaiDangKyID ASC), 
    CONSTRAINT [FK_HOINGHI_GUIBAIDANGKY_DANHMUC_KHOAPHONG] FOREIGN KEY (DMKhoaPhongID) REFERENCES DANHMUC_KHOAPHONG(DMKhoaPhongID)
)

GO

CREATE NONCLUSTERED INDEX [IX_HOINGHI_GUIBAIDANGKY_HoiNghiID] ON [dbo].[HOINGHI_GUIBAIDANGKY] (HoiNghiID ASC)
