CREATE TABLE [dbo].[HOINGHI_DANGKY]
(	  DangKyHoiNghiID INT NOT NULL IDENTITY 
	 ,TenBai NVARCHAR(1000)
	 ,ChuyenKhoa NVARCHAR(1000)
	 ,BaoCaoVien NVARCHAR(1000)
	 ,SoDT_BCV NVARCHAR(1000)
	 ,Email_BCV NVARCHAR(1000)
	 ,ChucDanh NVARCHAR(1000)
	 ,DMKhoaPhongID INT
	 ,DMKhoiID INT--BANGDANHMUCKHOI
	 ,CongSu NVARCHAR(1000)
	 ,LoaiBaoCao INT NULL--1:Hoi nghi,2:Nghiem thu,3:Dang tap chi
	 ,DangTapChi INT --1:TRONG NUOC,2:NUOC NGOAI
	 ,TapChiDang BIT  NOT NULL CONSTRAINT DF_HOINGHI_DANGKY_TapChiDang DEFAULT 1
	 ,NhanXet NVARCHAR(1000)
	 ,GhiChu NVARCHAR(1000)
	 ,HoiNghiID INT
	,CONSTRAINT PK_HOINGHI_DANGKY_ToChucDangKyID PRIMARY KEY  CLUSTERED (DangKyHoiNghiID ASC), 
     CONSTRAINT [FK_CHOINGHI_DANGKY_DANHMUC_KHOAPHONG] FOREIGN KEY (DMKhoaPhongID) REFERENCES DANHMUC_KHOAPHONG(DMKhoaPhongID), 
     CONSTRAINT [FK_HOINGHI_DANGKY_DANHMUC_KHOI] FOREIGN KEY (DMKhoiID) REFERENCES DANHMUC_KHOI(DMKhoiID), 
     CONSTRAINT [FK_HOINGHI_DANGKY_CHOINGHI_DANGKY] FOREIGN KEY (HoiNghiID) REFERENCES HOINGHI_DANGKY(DangKyHoiNghiID)
)

GO

CREATE NONCLUSTERED INDEX [IX_HOINGHI_DANGKY_DMKhoaPhongID] ON [dbo].[HOINGHI_DANGKY] (DMKhoaPhongID ASC)
GO
CREATE NONCLUSTERED INDEX [IX_HOINGHI_DANGKY_DMKhoiID] ON [dbo].[HOINGHI_DANGKY] (DMKhoiID ASC)
GO
CREATE NONCLUSTERED INDEX [IX_HOINGHI_DANGKY_HoiNghiID] ON [dbo].[HOINGHI_DANGKY] (HoiNghiID ASC)