CREATE TABLE [dbo].[HOINGHI_GHINHANKETQUA]
(
	 GhiNhanKetQuaID INT NOT NULL IDENTITY  
	,HoiNghiID  INT
	,KetQua NVARCHAR(1000)
	,NhanXet NVARCHAR(1000)
	,[NgayGhiNhan] DATETIME NULL, 
    CONSTRAINT PK_HOINGHI_GHINHANKETQUA_GhiNhanKetQuaID PRIMARY KEY  CLUSTERED (GhiNhanKetQuaID ASC)
	,CONSTRAINT [FK_HOINGHI_GHINHANKETQUA_HOINGHI_DANGKY] FOREIGN KEY (HoiNghiID) REFERENCES HOINGHI_TOCHUCMODOT(HoiNghiID) 
)

GO

CREATE NONCLUSTERED INDEX [IX_HOINGHI_GHINHANKETQUA_HoiNghiID] ON [dbo].[HOINGHI_GHINHANKETQUA] (HoiNghiID asc)
