CREATE TABLE [dbo].[HOINGHI_DUYEBAIDANGKY]
(
	 DuyetBaiDangKyID INT NOT NULL IDENTITY 
	,BoSung BIT  NOT NULL CONSTRAINT DF_HOINGHI_DUYEBAIDANGKY_BoSung DEFAULT 1--0:Khong bo sung,1:co bo sung
	,KinhPhi MONEY NULL
	,NgayNhan Date
	,NguoiNhan NVARCHAR(1000)
	,NguoiNop NVARCHAR(1000)
	,Duyet BIT  NOT NULL CONSTRAINT DF_HOINGHI_DUYEBAIDANGKY_Duyet DEFAULT 1
	,HoiNghiID INT--
	,CONSTRAINT PK_HOINGHI_DUYEBAIDANGKY_DuyetBaiDangKyID PRIMARY KEY  CLUSTERED (DuyetBaiDangKyID ASC)
	,CONSTRAINT [FK_HOINGHI_DUYEBAIDANGKY_HOINGHI_DANGKY] FOREIGN KEY (HoiNghiID) REFERENCES HOINGHI_TOCHUCMODOT(HoiNghiID)
)
GO
CREATE NONCLUSTERED INDEX [IX_HOINGHI_DUYEBAIDANGKY_HoiNghiID] ON [dbo].[HOINGHI_DUYEBAIDANGKY] (HoiNghiID ASC)
