CREATE TABLE DANHMUC_KHOI
(
	DMKhoiID					INT NOT NULL IDENTITY,
 	MaKhoi						NVARCHAR(1000) NULL,
 	TenKhoi						NVARCHAR(1000) NULL,
 	Active						BIT NOT NULL CONSTRAINT DF_DANHMUC_KHOI_Active DEFAULT 1,
	CONSTRAINT PK_DANHMUC_KHOI_DMKhoiID PRIMARY KEY  CLUSTERED (DMKhoiID ASC),
)
GO