CREATE TABLE [dbo].[DANHMUC_LOAIHOSO]
(
	 DMLoaiHoSoID			INT NOT NULL IDENTITY,
	 MaLoaiHoSo				NVARCHAR(1000) NULL,
	 TenLoaiHoSo			NVARCHAR(1000) NULL,
	 Active					BIT NOT NULL CONSTRAINT DF_DANHMUC_LOAIHOSO_Active  DEFAULT 1,
	 CONSTRAINT PK_DANHMUC_LOAIHOSO_DMLoaiHoSoID PRIMARY KEY CLUSTERED (DMLoaiHoSoID ASC),
)
Go