CREATE TABLE [dbo].[DANHMUC_HOIDONG_NHIEMKY_THANHVIEN]
(
	ThanhVienNhiemKyID					INT NOT NULL IDENTITY,
	MaThanhVien							NVARCHAR(1000) NULL,
	TenThanhVien						NVARCHAR(1000) NULL,
	ThongTinLienLac						NVARCHAR(1000) NULL,
	ChucVuID							int NULL,
	NoiCongTac							NVARCHAR(1000) NULL,
	NhiemVuTrongHD						NVARCHAR(1000) NULL,
	Active								bit NOT NULL CONSTRAINT DF_DANHMUC_HOIDONG_NHIEMKY_THANHVIEN_Active DEFAULT 1,
	CONSTRAINT PK_DANHMUC_HOIDONG_NHIEMKY_THANHVIEN_ThanhVienNhiemKyID PRIMARY KEY CLUSTERED (ThanhVienNhiemKyID ASC), 
    CONSTRAINT FK_DANHMUC_HOIDONG_NHIEMKY_THANHVIEN_ToTable FOREIGN KEY (ChucVuID) REFERENCES DANHMUC_CHUCVU(DMChucVuID),
)

GO

CREATE NONCLUSTERED INDEX [IX_DANHMUC_HOIDONG_NHIEMKY_THANHVIEN_ChucVuID] ON [dbo].[DANHMUC_HOIDONG_NHIEMKY_THANHVIEN] (ChucVuID ASC)
Go