CREATE TABLE DANHMUC_CHUCVU
( 
	DMChucVuID				INT NOT NULL IDENTITY,
	MaChucVu				nvarchar(1000)  NULL ,
	TenChucVu				nvarchar(1000)  NULL ,
	Active					BIT NOT NULL CONSTRAINT DF_DANHMUC_CHUCVU_Active DEFAULT 1,
	CONSTRAINT PK_DANHMUC_CHUCVU_DMChucVuID PRIMARY KEY  CLUSTERED (DMChucVuID ASC)
)
Go
