CREATE TABLE DANHMUC_HOCHAMHOCVI
( 
	DMHocHamHocViID				INT NOT NULL IDENTITY,
	MaHocHamHocVi				nvarchar(1000)  NULL ,
	TenHocHamHocVi				nvarchar(1000)  NULL ,
	Active						BIT NOT NULL CONSTRAINT DF_DANHMUC_HOCHAMHOCVI_Active DEFAULT 1,
	CONSTRAINT PK_DANHMUC_HOCHAMHOCVI_DMHocHamHocViID PRIMARY KEY  CLUSTERED (DMHocHamHocViID ASC)
)
GO