CREATE TABLE [dbo].[DANHMUC_TINHTRANGDETAI]
(
	DMTinhTrangDeTaiID					INT NOT NULL IDENTITY,
	MaTinhTrangDeTai					nvarchar(1000)  NULL ,
	TenTinhTrangDeTai					nvarchar(1000)  NULL ,
	Active								BIT NOT NULL CONSTRAINT DF_DANHMUC_TINHTRANGDETAI_Active DEFAULT 1,
	CONSTRAINT PK_DANHMUC_TINHTRANGDETAI_DMTinhTrangDeTaiID PRIMARY KEY  CLUSTERED (DMTinhTrangDeTaiID ASC),
)
GO
