CREATE TABLE DANHMUC_NGUONKINHPHI
(
	DMNguonKinhPhiID			int NOT NULL IDENTITY,
	MaNguonKinhPhi				nvarchar(1000) NULL,
	TenNguonKinhPhi				nvarchar(1000) NULL,
	Active						bit NOT NULL CONSTRAINT DF_DANHMUC_NGUONKINHPHI_Active DEFAULT 1,
	CONSTRAINT PK_DANHMUC_NGUONKINHPHI PRIMARY KEY CLUSTERED (DMNguonKinhPhiID ASC)
)
GO
