CREATE TABLE DANHMUC_CANBOTHUCHIEN
(
	CanBoThucHienID					int NOT NULL IDENTITY,
	MaCanBoThucHien					nvarchar(1000),
	HoTen							nvarchar(1000) NULL,
	HocHamHocViID					int NULL,			--ref DM HOCHAMHOCVI
	ChucDanhKhoaHocID				int NULL,			--ref DM CHUCDANHKHOAHOC
	DiaChiCoQuan					nvarchar(1000) NULL,
	DienThoai						nvarchar(1000) NULL,
	DiaChiNhaRieng					nvarchar(1000) NULL,
	Email							nvarchar(1000) NULL,
	Fax								nvarchar(1000) NULL,
	GioiTinh						BIT NOT NULL CONSTRAINT DF_DANHMUC_CANBOTHUCHIEN_GioiTinh DEFAULT 1,
	ChucVuID						int NULL,			--ref DM Chuc Vu
	KhoaPhongID						int NULL,			--ref DM KhoaPhong
	CONSTRAINT PK_DANHMUC_CANBOTHUCHIEN_CanBoThucHienID PRIMARY KEY CLUSTERED (CanBoThucHienID ASC),
	CONSTRAINT FK_DANHMUC_CANBOTHUCHIEN_HocHamHocViID FOREIGN KEY (HocHamHocViID) REFERENCES DANHMUC_HOCHAMHOCVI(DMHocHamHocViID),
	CONSTRAINT FK_DANHMUC_CANBOTHUCHIEN_ChucDanhKhoaHocID FOREIGN KEY (ChucDanhKhoaHocID) REFERENCES DANHMUC_CHUCDANHKHOAHOC(DMChucDanhKhoaHocID),
	CONSTRAINT FK_DANHMUC_CANBOTHUCHIEN_ChucVuID FOREIGN KEY (ChucVuID) REFERENCES DANHMUC_CHUCVU(DMChucVuID),
	CONSTRAINT FK_DANHMUC_CANBOTHUCHIEN_KhoaPhongID FOREIGN KEY (KhoaPhongID) REFERENCES DANHMUC_KHOAPHONG(DMKhoaPhongID)
)
GO

CREATE NONCLUSTERED INDEX IX_DANHMUC_CANBOTHUCHIEN_HocHamHocViID ON DANHMUC_CANBOTHUCHIEN
(
	HocHamHocViID ASC
)
GO

CREATE NONCLUSTERED INDEX IX_DANHMUC_CANBOTHUCHIEN_ChucDanhKhoaHocID ON DANHMUC_CANBOTHUCHIEN
(
	ChucDanhKhoaHocID ASC
)
GO

CREATE NONCLUSTERED INDEX IX_DANHMUC_CANBOTHUCHIEN_ChucVuID ON DANHMUC_CANBOTHUCHIEN
(
	ChucVuID ASC
)
GO

CREATE NONCLUSTERED INDEX IX_DANHMUC_CANBOTHUCHIEN_KhoaPhongID ON DANHMUC_CANBOTHUCHIEN
(
	KhoaPhongID ASC
)
GO