CREATE TABLE [dbo].[DANHMUC_LOAIVANBANDINHKEM]
(
	LoaiVanBanDinhKemID int NOT NULL IDENTITY,
	MaVanBanDinhKem nvarchar(1000) NULL,
	TenVanBanDinhKem nvarchar(1000) NULL,
	LoaiQuyTrinh int NULL,
	Form int NULL,-- (Enum)Cho biết đang ở form nào
	Active BIT NOT NULL CONSTRAINT DF_DANHMUC_LOAIVANBANDINHKEM_Active DEFAULT 1,
	CONSTRAINT PK_DANHMUC_LOAIVANBANDINHKEM_LoaiVanBanDinhKemID PRIMARY KEY CLUSTERED (LoaiVanBanDinhKemID ASC)
)
GO
