CREATE TABLE THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET
(
	KiemTraGiamSatChiTietID int NOT NULL IDENTITY,
	HoiDongID int NULL,--ref HOIDONG from LYNH
	KiemTraGiamSatID int NULL,--ref KIEMTRAGIAMSAT
	NgayKiemTra date NULL,
	GhiChu nvarchar(1000) NULL,
	CONSTRAINT PK_THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET_KiemTraGiamSatChiTietID PRIMARY KEY CLUSTERED (KiemTraGiamSatChiTietID ASC),
	CONSTRAINT FK_THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET_KiemTraGiamSatID FOREIGN KEY (KiemTraGiamSatID) REFERENCES THUCHIENDETAI_KIEMTRAGIAMSAT(KiemTraGiamSatID),
	CONSTRAINT FK_THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET_HoiDongID FOREIGN KEY (HoiDongID) REFERENCES HOIDONG_YEUCAU_XETDUYET(HoiDongID)
)
GO

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET_KiemTraGiamSatID ON THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET
( 
	KiemTraGiamSatID         ASC
)
go

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET_HoiDongID ON THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET
( 
	HoiDongID         ASC
)
go