CREATE TABLE THUCHIENDETAI_DENGHIDIEUCHINHNOIDUNG_CHITIET
(
	DeNghiDieuChinhNoiDungChiTietID int NOT NULL IDENTITY,
	LoaiDieuChinh int NULL,--Enum
	NgayDeNghi date NULL,
	NoiDungDieuChinh nvarchar(1000) NULL,
	KetQuaDeNghiDieuChinh bit NOT NULL CONSTRAINT DF_THUCHIENDETAI_DENGHIDIEUCHINHNOIDUNG_CHITIET_KetQuaDeNghiDieuChinh DEFAULT 1,
	DeNghiDieuChinhNoiDungID int NULL,--ref DENGHIDIEUCHINHNOIDUNG
	GhiChu nvarchar(1000) NULL,
	CONSTRAINT PK_THUCHIENDETAI_DENGHIDIEUCHINHNOIDUNG_CHITIET_DeNghiDieuChinhNoiDungChiTietID PRIMARY KEY CLUSTERED (DeNghiDieuChinhNoiDungChiTietID ASC),
	CONSTRAINT FK_THUCHIENDETAI_DENGHIDIEUCHINHNOIDUNG_CHITIET_DeNghiDieuChinhNoiDungID FOREIGN KEY (DeNghiDieuChinhNoiDungID) REFERENCES THUCHIENDETAI_DENGHIDIEUCHINHNOIDUNG(DeNghiDieuChinhNoiDungID)
)
GO

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_DENGHIDIEUCHINHNOIDUNG_CHITIET_DeNghiDieuChinhNoiDungID ON THUCHIENDETAI_DENGHIDIEUCHINHNOIDUNG_CHITIET
( 
	DeNghiDieuChinhNoiDungID         ASC
)
go