CREATE TABLE THUCHIENDETAI_BAOCAODINHKY
(
	BaoCaoDinhKyID int NOT NULL IDENTITY,
	DeTaiID int NULL,--ref DANGKYDETAI	
	GhiChu nvarchar(1000) NULL,
	CONSTRAINT PK_THUCHIENDETAI_BAOCAODINHKY_BaoCaoDinhKyID PRIMARY KEY CLUSTERED (BaoCaoDinhKyID ASC),
	CONSTRAINT FK_THUCHIENDETAI_BAOCAODINHKY_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_BAOCAODINHKY_DeTaiID ON THUCHIENDETAI_BAOCAODINHKY
( 
	DeTaiID         ASC
)
go