CREATE TABLE THUCHIENDETAI_BAOCAODINHKY_CHITIET
(
	BaoCaoDinhKyChiTietID int NOT NULL IDENTITY,
	BaoCaoDinhKyID int NULL,--ref THUCHIENDETAI_BAOCAODINHKY
	KyBaoCao int NULL,
	NgayBaoCao date NULL,
	NoiDungBaoCao nvarchar(1000) NULL,
	VanDeTonTai nvarchar(1000) NULL,
	DuKienCanTrienKhai nvarchar(1000) NULL,
	KetLuan nvarchar(1000) NULL,
	CONSTRAINT THUCHIENDETAI_BAOCAODINHKY_CHITIET_BaoCaoDinhKyChiTietID PRIMARY KEY CLUSTERED (BaoCaoDinhKyChiTietID ASC),
	CONSTRAINT THUCHIENDETAI_BAOCAODINHKY_CHITIET_BaoCaoDinhKyID FOREIGN KEY (BaoCaoDinhKyID) REFERENCES THUCHIENDETAI_BAOCAODINHKY(BaoCaoDinhKyID)
)
GO

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_BAOCAODINHKY_CHITIET_BaoCaoDinhKyID ON THUCHIENDETAI_BAOCAODINHKY_CHITIET
( 
	BaoCaoDinhKyID         ASC
)
go
