CREATE TABLE THUCHIENDETAI_KIEMTRAGIAMSAT
(
	KiemTraGiamSatID int NOT NULL IDENTITY,
	CapGiamSat int NULL,--Enum
	--NgayGiamSat date NULL,
	GhiChu nvarchar(1000) NULL,
	DeTaiID int NULL,--ref DANGKYDETAI
	CONSTRAINT PK_THUCHIENDETAI_KIEMTRAGIAMSAT_KiemTraGiamSatID PRIMARY KEY CLUSTERED (KiemTraGiamSatID ASC),
	CONSTRAINT FK_THUCHIENDETAI_KIEMTRAGIAMSAT_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_KIEMTRAGIAMSAT_DeTaiID ON THUCHIENDETAI_KIEMTRAGIAMSAT
( 
	DeTaiID         ASC
)
go
