CREATE TABLE THUCHIENDETAI_TOCHUCHOINGHIHOITHAO_CHITIET
(
	ToChucHoiNghiHoiThaoChiTietID int NOT NULL IDENTITY,
	ToChucHoiNghiHoiThaoID int NULL,--ref THUCHIENDETAI_TOCHUCHOINGHIHOITHAO
	HoiNghiHoiThaoID int NULL,--ref HOINGHIHOITHAO LYNH
	GhiChu nvarchar(1000) NULL,
	CONSTRAINT PK_THUCHIENDETAI_TOCHUCHOINGHIHOITHAO_CHITIET_ToChucHoiNghiHoiThaoChiTietID PRIMARY KEY CLUSTERED (ToChucHoiNghiHoiThaoChiTietID ASC),
	CONSTRAINT FK_THUCHIENDETAI_TOCHUCHOINGHIHOITHAO_CHITIET_ToChucHoiNghiHoiThaoID FOREIGN KEY (ToChucHoiNghiHoiThaoID) REFERENCES THUCHIENDETAI_TOCHUCHOINGHIHOITHAO(ToChucHoiNghiHoiThaoID),
	CONSTRAINT FK_THUCHIENDETAI_TOCHUCHOINGHIHOITHAO_CHITIET_HoiNghiHoiThaoID FOREIGN KEY (HoiNghiHoiThaoID) REFERENCES HOINGHI_TOCHUCMODOT(HoiNghiID)
)
GO

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_TOCHUCHOINGHIHOITHAO_CHITIET_ToChucHoiNghiHoiThaoID ON THUCHIENDETAI_TOCHUCHOINGHIHOITHAO_CHITIET
( 
	ToChucHoiNghiHoiThaoID         ASC
)
go

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_TOCHUCHOINGHIHOITHAO_CHITIET_HoiNghiHoiThaoID ON THUCHIENDETAI_TOCHUCHOINGHIHOITHAO_CHITIET
( 
	HoiNghiHoiThaoID         ASC
)
go