CREATE TABLE THUCHIENDETAI_XETDUYETHOIDONGKHKT_CHITIET
(
	XetDuyetHoiDongKHKTChiTietID int NOT NULL IDENTITY,
	HoiDongID int NULL,--ref HOIDONG from LYNH
	XetDuyetHoiDongKHKTID int NULL,--ref XETDUYETHOIDONGKHKT
	GhiChu nvarchar(1000) NULL,
	CONSTRAINT PK_THUCHIENDETAI_XETDUYETHOIDONGKHKT_CHITIET_XetDuyetHoiDongKHKTChiTietID PRIMARY KEY CLUSTERED (XetDuyetHoiDongKHKTChiTietID ASC),
	CONSTRAINT FK_THUCHIENDETAI_XETDUYETHOIDONGKHKT_CHITIET_XetDuyetHoiDongKHKTID FOREIGN KEY (XetDuyetHoiDongKHKTID) REFERENCES THUCHIENDETAI_XETDUYETHOIDONGKHKT(XetDuyetHoiDongKHKTID),
	CONSTRAINT FK_THUCHIENDETAI_XETDUYETHOIDONGKHKT_CHITIET_HoiDongID FOREIGN KEY (HoiDongID) REFERENCES HOIDONG_YEUCAU_XETDUYET(HoiDongID)
)
GO

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_XETDUYETHOIDONGKHKT_CHITIET_HoiDongID ON THUCHIENDETAI_XETDUYETHOIDONGKHKT_CHITIET
( 
	HoiDongID         ASC
)
go

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_XETDUYETHOIDONGKHKT_CHITIET_XetDuyetHoiDongKHKTID ON THUCHIENDETAI_XETDUYETHOIDONGKHKT_CHITIET
( 
	XetDuyetHoiDongKHKTID         ASC
)
go