CREATE TABLE THUCHIENDETAI_XETDUYETHOIDONGKHKT
(
	XetDuyetHoiDongKHKTID int NOT NULL IDENTITY,
	DeTaiID int NULL,--ref DANGKYDETAI
	GhiChu nvarchar(1000) NULL,
	CONSTRAINT PK_THUCHIENDETAI_XETDUYETHOIDONGKHKT_XetDuyetHoiDongKHKTID PRIMARY KEY CLUSTERED (XetDuyetHoiDongKHKTID ASC),
	CONSTRAINT FK_THUCHIENDETAI_XETDUYETHOIDONGKHKT_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_THUCHIENDETAI_XETDUYETHOIDONGKHKT_DeTaiID ON THUCHIENDETAI_XETDUYETHOIDONGKHKT
( 
	DeTaiID         ASC
)
go