CREATE TABLE DANGKYDETAI_CONGSUTHAMGIA
(
	CongSuThamGiaID int NOT NULL IDENTITY,
	DeTaiID int NULL,--ref DANGKYDETAI
	CanBoThucHienID int NULL,--ref DANGKYDETAI_CANBOTHUCHIEN
	CONSTRAINT PK_DANGKYDETAI_CONGSUTHAMGIA_CongSuThamGiaID PRIMARY KEY CLUSTERED (CongSuThamGiaID ASC),
	CONSTRAINT FK_DANGKYDETAI_CONGSUTHAMGIA_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID),
	CONSTRAINT FK_DANGKYDETAI_CONGSUTHAMGIA_CanBoThucHienID FOREIGN KEY (CanBoThucHienID) REFERENCES DANHMUC_CANBOTHUCHIEN(CanBoThucHienID)
)
GO
CREATE NONCLUSTERED INDEX IX_DANGKYDETAI_CONGSUTHAMGIA_DeTaiID ON DANGKYDETAI_CONGSUTHAMGIA
( 
	DeTaiID         ASC
)
go

CREATE NONCLUSTERED INDEX IX_DANGKYDETAI_CONGSUTHAMGIA_CanBoThucHienID ON DANGKYDETAI_CONGSUTHAMGIA
( 
	CanBoThucHienID         ASC
)
go