CREATE TABLE DANGKYDETAI_DETAINHANH--gridview trong Form GHINHANKETQUA
(
	DeTaiNhanhID int NOT NULL IDENTITY,
	GhiNhanKetQuaID int NULL,--ref GHINHANKETQUA
	TenDeTaiNhanh nvarchar(1000) NULL,
	CanBoThucHienID int NULL,--ref CANBOTHUCHIEN
	CONSTRAINT PK_DANGKYDETAI_DETAINHANH_DeTaiNhanhID PRIMARY KEY CLUSTERED (DeTaiNhanhID ASC),
	CONSTRAINT FK_DANGKYDETAI_DETAINHANH_GhiNhanKetQuaID FOREIGN KEY (GhiNhanKetQuaID) REFERENCES XETDUYETDETAI_GHINHANKETQUA(GhiNhanKetQuaID),
	CONSTRAINT FK_DANGKYDETAI_DETAINHANH_CanBoThucHienID FOREIGN KEY (CanBoThucHienID) REFERENCES DANHMUC_CANBOTHUCHIEN(CanBoThucHienID),
)
GO

CREATE NONCLUSTERED INDEX IX_DANGKYDETAI_DETAINHANH_GhiNhanKetQuaID ON DANGKYDETAI_DETAINHANH
( 
	GhiNhanKetQuaID         ASC
)
go

CREATE NONCLUSTERED INDEX IX_DANGKYDETAI_DETAINHANH_CanBoThucHienID ON DANGKYDETAI_DETAINHANH
( 
	CanBoThucHienID         ASC
)
go