CREATE TABLE NGHIEMTHU_NGHIEMTHUDETAICAPCOSO
(
	NghiemThuDeTaiCapCoSoID int NOT NULL IDENTITY,
	DeTaiID int NULL,--ref DANGKYDETAI
	NgayBaoVeBaoCaoNghiemThu date NULL,
	HoiDongID int NULL,--ref HOIDONG from LYNH
	KetQuaDeTai int NULL,-- Enum
	KetQuaNghiemThuCapCoSo bit NULL,
	CoChinhSuaBoSung bit NOT NULL CONSTRAINT DF_NGHIEMTHU_NGHIEMTHUDETAICAPCOSO_CoChinhSuaBoSung DEFAULT 1,
	[GhiChu] NVARCHAR(1000) NULL, 
    CONSTRAINT PK_NGHIEMTHU_NGHIEMTHUDETAICAPCOSO_NghiemThuDeTaiCapCoSoID PRIMARY KEY CLUSTERED (NghiemThuDeTaiCapCoSoID ASC),
	CONSTRAINT FK_NGHIEMTHU_NGHIEMTHUDETAICAPCOSO_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID),
	CONSTRAINT FK_NGHIEMTHU_NGHIEMTHUDETAICAPCOSO_HoiDongID FOREIGN KEY (HoiDongID) REFERENCES HOIDONG_YEUCAU_XETDUYET(HoiDongID)
)
GO

CREATE NONCLUSTERED INDEX IX_NGHIEMTHU_NGHIEMTHUDETAICAPCOSO_DeTaiID ON NGHIEMTHU_NGHIEMTHUDETAICAPCOSO
( 
	DeTaiID         ASC
)
go


CREATE NONCLUSTERED INDEX IX_NGHIEMTHU_NGHIEMTHUDETAICAPCOSO_HoiDongID ON NGHIEMTHU_NGHIEMTHUDETAICAPCOSO
( 
	HoiDongID         ASC
)
go
