CREATE TABLE NGHIEMTHU_DENGHICAPQUANLY
(
	DeNghiNghiemThuCapQuanLyID int NOT NULL IDENTITY,
	NgayDeNghi date NULL,
	GhiChu nvarchar(1000) NULL,
	DeTaiID int NULL,--ref DANGKYDETAI
	CONSTRAINT PK_NGHIEMTHU_DENGHICAPQUANLY_DeNghiNghiemThuCapQuanLyID PRIMARY KEY CLUSTERED (DeNghiNghiemThuCapQuanLyID ASC),
	CONSTRAINT FK_NGHIEMTHU_DENGHICAPQUANLY_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_NGHIEMTHU_DENGHICAPQUANLY_DeTaiID ON NGHIEMTHU_DENGHICAPQUANLY
( 
	DeTaiID         ASC
)
go
