CREATE TABLE NGHIEMTHU_NGHIEMTHUDETAICAPQUANLY
(
	NghiemThuDeTaiCapQuanLyID int NOT NULL IDENTITY,
	DeTaiID int NULL,--ref DANGKYDETAI
	NgayNghiemThu date NULL,
	KetQuaNghiemThuCapQuanLy bit NOT NULL CONSTRAINT DF_NGHIEMTHU_NGHIEMTHUDETAICAPQUANLY_KetQuaNghiemThuCapQuanLy DEFAULT 1,
	[GhiChu] NVARCHAR(1000) NULL, 
    CONSTRAINT PK_NGHIEMTHU_NGHIEMTHUDETAICAPQUANLY_NghiemThuDeTaiCapQuanLyID PRIMARY KEY CLUSTERED (NghiemThuDeTaiCapQuanLyID ASC),
	CONSTRAINT FK_NGHIEMTHU_NGHIEMTHUDETAICAPQUANLY_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_NGHIEMTHU_NGHIEMTHUDETAICAPQUANLY_DeTaiID ON NGHIEMTHU_NGHIEMTHUDETAICAPQUANLY
( 
	DeTaiID         ASC
)
go