CREATE TABLE NGHIEMTHU_DENGHICAPCOSO
(
	DeNghiNghiemThuCapCoSoID int NOT NULL IDENTITY,
	NgayDeNghi date NULL,
	GhiChu nvarchar(1000) NULL,
	DeTaiID int NULL,--ref DANGKYDETAI
	CONSTRAINT PK_NGHIEMTHU_DENGHICAPCOSO_DeNghiNghiemThuCapCoSoID PRIMARY KEY CLUSTERED (DeNghiNghiemThuCapCoSoID ASC),
	CONSTRAINT FK_NGHIEMTHU_DENGHICAPCOSO_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_NGHIEMTHU_DENGHICAPCOSO_DeTaiID ON NGHIEMTHU_DENGHICAPCOSO
( 
	DeTaiID         ASC
)
go
