CREATE TABLE [dbo].[DETAIBENNGOAI_BAOCAOHOANTAT]
(
	BaoCaoHoanTatID INT NOT NULL IDENTITY
	,DeTaiBenNgoaiID INT
	,ThoiGianLaySoLieu date
	,CONSTRAINT PK_DETAIBENNGOAI_BAOCAOHOANTAT_BaoCaoHoanTatID PRIMARY KEY  CLUSTERED (BaoCaoHoanTatID ASC), 
     CONSTRAINT [FK_DETAIBENNGOAI_BAOCAOHOANTAT_DETAIBENNGOAI_NHANYEUCAU] FOREIGN KEY (DeTaiBenNgoaiID) REFERENCES DETAIBENNGOAI_NHANYEUCAU(DeTaiBenNgoaiID), 
)

GO

CREATE NONCLUSTERED INDEX [IX_DETAIBENNGOAI_BAOCAOHOANTAT_DeTaiBenNgoaiID] ON [dbo].[DETAIBENNGOAI_BAOCAOHOANTAT] (DeTaiBenNgoaiID asc)
