CREATE TABLE [dbo].[DETAIBENNGOAI_NHANYEUCAU]
(
	DeTaiBenNgoaiID INT NOT NULL IDENTITY
	,MaDeTai NVARCHAR(1000) NULL
	,TenDeTai NVARCHAR(1000) NULL
	,NguoiHuongDan NVARCHAR(1000) NULL
	,ThoiGianThucHien_Tu Date NULL
	,ThoiGianThucHien_Den Date NULL
	,NgayHopHĐĐĐNCYSH DateTime NULL
	,ChuNhiemDeTai NVARCHAR(1000) NULL
	,DiaDiem  NVaRCHAR(1000) NULL
	,ThoiGianNghienCuu_Tu Date NULL
	,ThoiGianNghienCuu_Den Date NULL
	,ThoiGianChapThuan Date NULL
	,ThoiGianLaySoLieu_Tu Date NULL
	,ThoiGianLaySoLieu_Den Date NULL
	,LoaiDeTai INT NULL--1:NCS,CKII,CKI,Cao học,Đại học,Khác) 
	,DoiTuongNghienCuu NVARCHAR(1000) NULL
	,ThietKeNghienCuu NVARCHAR(1000) NULL
	,TrangThaiDeTaiBenNgoai INT NULL
	,DuThuTuc BIT NOT NULL CONSTRAINT DETAIBENNGOAI_NHANYEUCAU_DuThuTuc DEFAULT 1
	,[ThieuChapThuan] BIT	NOT NULL CONSTRAINT DETAIBENNGOAI_NHANYEUCAU_ThieuChapThuat DEFAULT 1
	,UserID int NULL
	,CONSTRAINT PK_DETAIBENNGOAI_NHANYEUCAU_DeTaiBenNgoaiID PRIMARY KEY  CLUSTERED (DeTaiBenNgoaiID ASC)

)
GO

CREATE FULLTEXT CATALOG [FTC_NhanYeuCauLaySoLieu_TenDeTai]
GO

CREATE FULLTEXT INDEX ON [dbo].[DETAIBENNGOAI_NHANYEUCAU] ([TenDeTai]) KEY INDEX [PK_DETAIBENNGOAI_NHANYEUCAU_DeTaiBenNgoaiID] ON [FTC_NhanYeuCauLaySoLieu_TenDeTai] WITH CHANGE_TRACKING AUTO

