CREATE TABLE [dbo].[DETAIBENNGOAI_LAMGIAYGIOITHIEU]
(
	 LamGiayGioiThieuID INT NOT NULL IDENTITY 
	,DeTaiBenNgoaiID INT
	,DMKhoaPhongID INT -- ref danh muc khoa phong GUI TOI PHONG NAO
   ,CONSTRAINT PK_DETAIBENNGOAI_LAMGIAYGIOITHIEU_LamGiayGioiThieuID PRIMARY KEY  CLUSTERED (LamGiayGioiThieuID ASC), 
    CONSTRAINT [FK_DETAIBENNGOAI_LAMGIAYGIOITHIEU_DETAIBENNGOAI_NHANYEUCAU] FOREIGN KEY (DeTaiBenNgoaiID) REFERENCES DETAIBENNGOAI_NHANYEUCAU(DeTaiBenNgoaiID), 
    CONSTRAINT [FK_DETAIBENNGOAI_LAMGIAYGIOITHIEU_DANHMUC_KHOAPHONG] FOREIGN KEY (DMKhoaPhongID) REFERENCES DANHMUC_KHOAPHONG(DMKhoaPhongID), 
)

GO

CREATE NONCLUSTERED INDEX [IX_DETAIBENNGOAI_LAMGIAYGIOITHIEU_DeTaiBenNgoaiID] ON [dbo].[DETAIBENNGOAI_LAMGIAYGIOITHIEU] (DeTaiBenNgoaiID asc)
GO
CREATE NONCLUSTERED INDEX [IX_DETAIBENNGOAI_LAMGIAYGIOITHIEU_DMKhoaPhongID] ON [dbo].[DETAIBENNGOAI_LAMGIAYGIOITHIEU] (DMKhoaPhongID asc)
