CREATE TABLE [dbo].[DETAIBENNGOAI_GIAMSATKIEMTRA_THANHVIEN]
(
	ThanhVienGiamSatID INT NOT NULL IDENTITY
	,MaThanhVien NVARCHAR(1000)
	,TenThanhVien NVARCHAR(1000)
	,ChucVu NVARCHAR(1000)
	,GiamSatKiemTraID INT
	,CONSTRAINT PK_DETAIBENNGOAI_GIAMSATKIEMTRA_THANHVIEN_ThanhVienGiamSatID PRIMARY KEY  CLUSTERED (ThanhVienGiamSatID ASC), 
    CONSTRAINT [FK_DETAIBENNGOAI_GIAMSATKIEMTRA_THANHVIEN_DETAIBENNGOAI_GIAMSATKIEMTRA] FOREIGN KEY (GiamSatKiemTraID) REFERENCES DETAIBENNGOAI_GIAMSATKIEMTRA(GiamSatKiemTraID), 
)

GO

CREATE NONCLUSTERED INDEX [IX_DETAIBENNGOAI_GIAMSATKIEMTRA_THANHVIEN_ThanhVienGiamSatID] ON [dbo].[DETAIBENNGOAI_GIAMSATKIEMTRA_THANHVIEN] (ThanhVienGiamSatID asc)
