CREATE PROC dbo.proc_SearchHoiNghi_LapChuongTrinh
	 @HoiNghiID NVARCHAR(100)
	,@Ngay nvarchar(100)
AS
	IF(ISDATE(@Ngay)>0)
		  SET @Ngay=CONVERT(DATE,@Ngay,103)
	ELSE
		 SET @Ngay='%'
	SELECT A.*,B.TrangThaiHoiNghi FROM(
	SELECT * FROM HOINGHI_LAPCHUONGTRINH NOLOCK WHERE HoiNghiID LIKE @HoiNghiID AND Ngay LIKE @Ngay) AS A
	INNER JOIN(SELECT *FROM HOINGHI_TOCHUCMODOT NOLOCK) AS B ON B.HoiNghiID=A.HoiNghiID
	 ORDER BY Ngay DESC
GO