CREATE PROCEDURE [dbo].[fpt_spPrint_DeTai_I]
	@DetaiId INT
AS
SELECT A.*,B.TenCapQuanLy,C.TenChucDanhKhoaHoc,D.TenHocHamHocVi FROM
(SELECT * FROM DETAI NOLOCK WHERE DeTaiID=@DetaiId) AS A
LEFT JOIN(SELECT * FROM DM_CAPQUANLY NOLOCK)AS B ON B.DMCapQuanLyID=A.DMCapQuanLyID
LEFT JOIN(SELECT * FROM DM_CHUCDANHKHOAHOC NOLOCK)AS C ON C.DMChucDanhKhoaHocID=A.CNDT_DMChucDanhKhoaHocID
LEFT JOIN(SELECT * FROM DM_HOCHAMHOCVI NOLOCK) AS D ON D.DMHocHamHocViID=A.CNDT_DMHocHamHocViID