CREATE TABLE [dbo].[HOIDONG_CHUANBI_CUOCHOP]
(
	[CuocHopID] INT NOT NULL IDENTITY
   ,HoiDongID INT  NULL
   ,ThoiGian DATETIME NULL
   ,DiaDiem NVARCHAR(1000) NULL
   ,LoaiXetDuyetID INT NULL--Enum
   ,CONSTRAINT PK_HOIDONG_CHUANBI_CUOCHOP_CuocHopID PRIMARY KEY CLUSTERED ([CuocHopID] ASC), 
    CONSTRAINT [FK_HOIDONG_CHUANBI_CUOCHOP_HOIDONG_YEUCAU_XETDUYET] FOREIGN KEY (HoiDongID) REFERENCES [HOIDONG_YEUCAU_XETDUYET](HoiDongID), 
  )

GO



CREATE NONCLUSTERED INDEX [IX_HOIDONG_CHUANBI_CUOCHOP_HoiDongID] ON [dbo].[HOIDONG_CHUANBI_CUOCHOP] ([HoiDongID] ASC)
