CREATE TABLE [dbo].[HOIDONG_YEUCAU_XETDUYET]
(
	 HoiDongID INT NOT NULL IDENTITY 
	,MaHoiDong NVarchar(1000) null
	,DMLoaiHoSoID INT NULL--- REF DANHMUC_LOAIHOSO
	,DoiTuongXetDuyet NVARCHAR(1000) NULL
	,DMKhoaPhongID INT NULL----TU BANG DANH MUC KHOA PHONG CUA TAM(Don vi de nghi)
	,ThoiGianDangKy DATE
	,TrangThaiHD int null--Enum
	,DayDuHoSo BIT NOT NULL CONSTRAINT DF_HOIDONG_YEUCAU_XETDUYET_DayDuHoSo DEFAULT 1
	,UserID int NULL
   ,CONSTRAINT PK_HOIDONG_YEUCAU_XETDUYET_HoiDongID PRIMARY KEY CLUSTERED (HoiDongID ASC)
   ,CONSTRAINT [FK_HOIDONG_YEUCAU_XETDUYET_DMLoaiHoSoID] FOREIGN KEY (DMLoaiHoSoID) REFERENCES [DANHMUC_LOAIHOSO](DMLoaiHoSoID)
   ,CONSTRAINT [FK_HOIDONG_YEUCAU_XETDUYET_DANHMUC_KHOAPHONG] FOREIGN KEY (DMKhoaPhongID) REFERENCES DANHMUC_KHOAPHONG(DMKhoaPhongID),
)
GO
CREATE NONCLUSTERED  INDEX [IX_HOIDONG_YEUCAU_XETDUYET_DMKhoaPhongID] ON [dbo].DANHMUC_KHOAPHONG (DMKhoaPhongID ASC)
go
CREATE NONCLUSTERED  INDEX [IX_HOIDONG_YEUCAU_XETDUYET_DMLoaiHoSoID] ON [dbo].[DANHMUC_LOAIHOSO] (DMLoaiHoSoID ASC)
