CREATE TABLE [dbo].[HOIDONG_GHINHAN_KETQUA_THANVIEN]
(
	 ThanhVienGhiNhanID INT NOT NULL IDENTITY
	,ThanhVienCuocHopID INT NULL
	,GhiNhanKetQuaID INT NULL
	,CONSTRAINT PK_HOIDONG_GHINHAN_KETQUA_THANVIEN_GhiNhan_CuocHop_ThanhVienID PRIMARY KEY CLUSTERED (ThanhVienGhiNhanID ASC), 
     CONSTRAINT [FK_HOIDONG_GHINHAN_KETQUA_THANVIEN_HOIDONG_CHUANBI_CUOCHOP_THANHVIEN] FOREIGN KEY (ThanhVienCuocHopID) REFERENCES HOIDONG_CHUANBI_CUOCHOP_THANHVIEN([ThanhVienCuocHopID])
)

GO

CREATE NONCLUSTERED INDEX [IX_HOIDONG_GHINHAN_KETQUA_THANVIEN_GhiNhan_CuocHop_ThanhVienCuocHopID] ON [dbo].[HOIDONG_GHINHAN_KETQUA_THANVIEN] (ThanhVienCuocHopID ASC)
