CREATE TABLE [dbo].[HOIDONG_NHIEMKY_CHITIET]
(
  HDNhiemKyChiTietID INT NOT NULL IDENTITY
  ,HDNhiemKyID INT NULL 
  ,ThanhVienNhiemKyID INT  NULL
  ,CONSTRAINT PK_HOIDONG_NHIEMKY_CHITIET_HDNhiemKyChiTietID PRIMARY KEY CLUSTERED (HDNhiemKyChiTietID ASC)
 ,CONSTRAINT [FK_HOIDONG_NHIEMKY_CHITIET_HOIDONG_NHIEMKY] FOREIGN KEY ([HDNhiemKyID]) REFERENCES [HOIDONG_NHIEMKY](HDNhiemKyID)
 ,CONSTRAINT [FK_HOIDONG_NHIEMKY_CHITIET_DANHMUC_HOIDONG_NHIEMKY_THANHVIEN] FOREIGN KEY (ThanhVienNhiemKyID) REFERENCES DANHMUC_HOIDONG_NHIEMKY_THANHVIEN(ThanhVienNhiemKyID)
)

GO

CREATE NONCLUSTERED  INDEX [IX_HOIDONG_NHIEMKY_CHITIET_HDNhiemKyID] ON [dbo].[HOIDONG_NHIEMKY_CHITIET] (HDNhiemKyID ASC)
GO
CREATE NONCLUSTERED  INDEX [IX_HOIDONG_NHIEMKY_CHITIET_ThanhVienNhiemKyID] ON [dbo].DANHMUC_HOIDONG_NHIEMKY_THANHVIEN (ThanhVienNhiemKyID  ASC)
