CREATE TABLE [dbo].[HOIDONG_GHINHAN_KETQUA]
(
	GhiNhanKetQuaID INT NOT NULL IDENTITY
	,ThoiGian DateTime NULL
	,DiaDiem NVARCHAR(1000) NULL
	,KetLuan NVARCHAR(1000) NULL
	,[HoiDongID] INT NULL, 
    CONSTRAINT PK_HOIDONG_GHINHAN_KETQUA_GhiNhanKetQuaID PRIMARY KEY CLUSTERED (GhiNhanKetQuaID ASC), 
    CONSTRAINT [FK_HOIDONG_GHINHAN_KETQUA_HOIDONG_YEUCAU_XETDUYET] FOREIGN KEY (HoiDongID) REFERENCES HOIDONG_YEUCAU_XETDUYET(HoiDongID)
)

GO

CREATE NONCLUSTERED INDEX [IX_HOIDONG_GHINHAN_KETQUA_HoiDongID] ON [dbo].[HOIDONG_GHINHAN_KETQUA] (HoiDongID ASC)
