CREATE TABLE [dbo].[HOIDONG_CHONLUA]
(
	ChonLuaID INT NOT NULL IDENTITY
   ,HoiDongID INT  NULL --ref HOIDONG_YEUCAU_XETDUYET 
   ,LoaiHoiDong int NULL--1:DAO DUC;2 KY THUAT;3 CHUYEN MON
   ,NgayThanhLap Date NULL
   ,CONSTRAINT PK_HOIDONG_CHONLUA_ChonLuaID PRIMARY KEY CLUSTERED (ChonLuaID ASC)
   ,CONSTRAINT [FK_HOIDONG_CHONLUA_HoiDong_HoiDongID] FOREIGN KEY (HoiDongID) REFERENCES [HOIDONG_YEUCAU_XETDUYET](HoiDongID),
)
GO

CREATE NONCLUSTERED INDEX [IX_HOIDONG_CHONLUA_HoiDong_HoiDongID] ON [dbo].HOIDONG_CHONLUA (HoiDongID ASC)
