CREATE TABLE [dbo].[HOIDONG_CHONLUA_THANHVIEN]
(
	ThanhVienHDID INT NOT NULL IDENTITY
	,MaThanhVien  NVARCHAR(1000) NULL
	,TenThanhVien NVARCHAR(1000) NULL
	,ThongTinLienLac NVARCHAR(1000) NULL
	,ChucVuID int NULL--dm chuc vu cua Tam
	,NoiCongTac NVARCHAR(1000) NULL
	,NhiemVuTrongHD NVARCHAR(1000) NULL
	,[ChonLuaID] INT NULL--ref HOIDONG_CHONLUA
	,CONSTRAINT PK_HOIDONG_CHONLUA_THANHVIEN_HOIDONG_CHONLUA_THANHVIENID PRIMARY KEY CLUSTERED (ThanhVienHDID ASC), 
     CONSTRAINT [FK_HOIDONG_CHONLUA_THANHVIEN_HOIDONG_CHONLUA] FOREIGN KEY ([ChonLuaID]) REFERENCES [HOIDONG_CHONLUA](ChonLuaID)
)

GO

CREATE NONCLUSTERED INDEX [IX_HOIDONG_CHONLUA_THANHVIEN_THANHVIENID] ON [dbo].[HOIDONG_CHONLUA_THANHVIEN] (ThanhVienHDID ASC)
