CREATE TABLE [dbo].[HOIDONG_CHUANBI_CUOCHOP_THANHVIEN]
(
	 [ThanhVienCuocHopID] INT NOT NULL IDENTITY
	,[CuocHopID] INT NULL
	,ThanhVienHDID INT NULL, 
    CONSTRAINT [PK_HOIDONG_CHUANBI_CUOCHOP_THANHVIEN_ThanhVienID] PRIMARY KEY CLUSTERED (ThanhVienCuocHopID ASC), 
    CONSTRAINT [FK_HOIDONG_CHUANBI_CUOCHOP_THANHVIEN_HOIDONG_CHUANBI_CUOCHOP] FOREIGN KEY ([CuocHopID]) REFERENCES HOIDONG_CHUANBI_CUOCHOP(CUOCHOPID), 
    CONSTRAINT [FK_HOIDONG_CHUANBI_CUOCHOP_THANHVIEN_HOIDONG_CHONLUA_THANHVIEN] FOREIGN KEY ([ThanhVienHDID]) REFERENCES [HOIDONG_CHONLUA_THANHVIEN]([ThanhVienHDID]), 
)
GO


CREATE NONCLUSTERED INDEX [IX_HOIDONG_CHUANBI_CUOCHOP_CUOCHOPID] ON [dbo].[HOIDONG_CHUANBI_CUOCHOP_THANHVIEN] (CUOCHOPID ASC)
GO
CREATE NONCLUSTERED INDEX [IX_HOIDONG_CHUANBI_CUOCHOP_ThanhVienHDID] ON [dbo].[HOIDONG_CHUANBI_CUOCHOP_THANHVIEN] ([ThanhVienHDID] ASC)
