CREATE PROCEDURE [dbo].[proc_DanhSachHoiDongLuaChon]
	@LoaiHoiDong VARCHAR(50)
AS
	SELECT
	 ChonLuaID,A.HoiDongID,LoaiHoiDong,NgayThanhLap,MaHoiDong,DoiTuongXetDuyet
	 ,DMKhoaPhongID,DMLoaiHoSoID
	 FROM(SELECT * FROM HOIDONG_CHONLUA NOLOCK) AS A
	INNER JOIN(SELECT * FROM HOIDONG_YEUCAU_XETDUYET NOLOCK) AS B ON B.HoiDongID=A.HoiDongID
	INNER JOIN(SELECT * FROM HOIDONG_CHUANBI_CUOCHOP NOLOCK)AS C ON C.HoiDongID=A.HoiDongID 
	WHERE  LoaiHoiDong LIKE '%'
	ORDER BY MaHoiDong,NgayThanhLap