CREATE PROC proc_DanhSachThanVienCuocHop_HoiDongID
@HoiDongID INT
AS
   SELECT DISTINCT B.*,C.* FROM(SELECT * FROM HOIDONG_CHONLUA NOLOCK WHERE HoiDongID=@HoiDongID) AS A
	INNER JOIN(SELECT * FROM HOIDONG_CHONLUA_THANHVIEN NOLOCK) AS B ON B.ChonLuaID=A.ChonLuaID
	INNER JOIN(SELECT * FROM HOIDONG_CHUANBI_CUOCHOP_THANHVIEN NOLOCK) AS C ON C.ThanhVienHDID=B.ThanhVienHDID
   ORDER BY MaThanhVien,TenThanhVien