	CREATE PROC proc_DanhSachThanVienHoiDongChonLua
		@HoiDongID INT
	AS
	SELECT B.* FROM(SELECT * FROM HOIDONG_CHONLUA NOLOCK WHERE HoiDongID=@HoiDongID) AS A
	INNER JOIN(SELECT * FROM HOIDONG_CHONLUA_THANHVIEN NOLOCK) AS B ON B.ChonLuaID=A.ChonLuaID
   ORDER BY MaThanhVien,TenThanhVien