CREATE PROC proc_DanhSachNhanVien_CuocHop
		@CuocHopID INT
	AS
	SELECT B.*,CuocHopID,ThanhVienCuocHopID FROM(SELECT * FROM HOIDONG_CHUANBI_CUOCHOP_THANHVIEN NOLOCK WHERE CuocHopID=@CuocHopID)AS A
	INNER JOIN(SELECT * FROM HOIDONG_CHONLUA_THANHVIEN NOLOCK) AS B ON B.ThanhVienHDID=A.ThanhVienHDID
	ORDER BY MaThanhVien,TenThanhVien