	CREATE PROC proc_DanhSachNhanVien_GhiNhanKetQua
		@GhiNhanID INT
	AS
	SELECT * FROM(SELECT * FROM HOIDONG_GHINHAN_KETQUA_THANVIEN NOLOCK)AS A
	INNER JOIN(SELECT * FROM HOIDONG_CHUANBI_CUOCHOP_THANHVIEN NOLOCK) AS B ON B.ThanhVienCuocHopID=A.ThanhVienCuocHopID
	INNER JOIN(SELECT * FROM HOIDONG_CHONLUA_THANHVIEN NOLOCK) AS C ON C.ThanhVienHDID=B.ThanhVienHDID
	ORDER BY MaThanhVien,TenThanhVien