CREATE PROCEDURE [dbo].[proc_Print_BanNhanXetKetQuaNghienCuu]
	@ID int
	--ID: KetQuaNghienCuuID
AS
BEGIN

	SET NOCOUNT ON;

	SELECT
		DT.TenDeTai,DT.MaSoDeTai,DT.CNDT_HoTen,CQL.TenCapQuanLy,
		DT.ThucHienTuNgay,DT.ThucHienDenNgay,DT.KinhPhi,
		HD.SoQuyetDinh,HD.NgayQuyetDinh,DVBH.TenDonViBanHanh,
		DS.HoTen,DS.HocHam,DS.HocVi,DS.ChuyenNganh,DS.DonVi,
		KQ.TC1,KQ.TC2,KQ.TC3,KQ.TC4,KQ.TC5,KQ.TC6,KQ.TC7,KQ.TC8,KQ.TC9,KQ.TC10,
		KQ.DanhGiaNhanXetChung,KQ.NoiDungThucHienKhongPhuHop,KQ.YKienHoiDong
	FROM
	(SELECT *
	FROM KETQUANGHIENCUU 
	WHERE KetQuaNghienCuuID = @ID) KQ
	INNER JOIN DETAI DT ON DT.DeTaiID = KQ.KQNC_DeTaiID
	INNER JOIN DM_CAPQUANLY CQL ON CQL.DMCapQuanLyID = DT.DMCapQuanLyID
	INNER JOIN DANHSACHHOIDONG DS ON DS.DanhSachHoiDongID = KQ.KQNC_DanhSachHoiDongID
	INNER JOIN HOIDONGNGHIEMTHU HD ON HD.HoiDongNghiemThuID = DS.HoiDongNghiemThuID
	INNER JOIN DM_DONVIBANHANH DVBH ON DVBH.DMDonViBanHanhID = HD.DMDonViBanHanhID
END
