CREATE PROCEDURE [dbo].[proc_Search_KiemTraGiamSat]
	@tenDeTai nvarchar(1000),
	@maDeTai nvarchar(1000),
	@chuNhiemDeTai int,
	@coQuanChuTri nvarchar(1000),
	@ngayKiemTra date
AS
BEGIN
	SET NOCOUNT ON;

	IF @tenDeTai IS NOT NULL
	BEGIN
		SELECT DISTINCT(KT.KiemTraGiamSatID),DKDT.DeTaiID,MaDeTai,TenDeTai,ThucHienTuNgay,ThucHienDenNgay,KinhPhiThucHien,CoQuanChuTri,MaCanBoThucHien,HoTen,TrangThaiDeTai
		FROM DANGKYDETAI DKDT 
		INNER JOIN FREETEXTTABLE(DANGKYDETAI,TenDeTai,@tenDeTai) as FTS_DKDT
		ON DKDT.DeTaiID = FTS_DKDT.[KEY]
		INNER JOIN DANHMUC_CANBOTHUCHIEN CBTH ON CBTH.CanBoThucHienID = DKDT.ChuNhiemDeTaiID
		INNER JOIN THUCHIENDETAI_KIEMTRAGIAMSAT KT ON KT.DeTaiID = DKDT.DeTaiID
		LEFT JOIN THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET CT ON CT.KiemTraGiamSatID = KT.KiemTraGiamSatID
		--LEFT JOIN : TRƯỜNG HỢP KHÔNG CÓ CHI TIET VAN LAY DUOC DU LIEU		
		AND (CBTH.CanBoThucHienID = @chuNhiemDeTai OR @chuNhiemDeTai IS NULL)
		AND (UPPER(LTRIM(RTRIM(DKDT.MaDeTai))) LIKE '%'+UPPER(LTRIM(RTRIM(@maDeTai)))+'%' OR @maDeTai IS NULL)  	
		AND (UPPER(LTRIM(RTRIM(DKDT.CoQuanChuTri))) LIKE '%' +UPPER(LTRIM(RTRIM(@coQuanChuTri)))+ '%' OR @coQuanChuTri IS NULL)
		AND (CT.NgayKiemTra = @ngayKiemTra OR @ngayKiemTra IS NULL)
	END
	ELSE
	BEGIN
		SELECT DISTINCT(KT.KiemTraGiamSatID),DKDT.DeTaiID,MaDeTai,TenDeTai,ThucHienTuNgay,ThucHienDenNgay,KinhPhiThucHien,CoQuanChuTri,MaCanBoThucHien,HoTen,TrangThaiDeTai
		FROM DANGKYDETAI DKDT 		
		INNER JOIN DANHMUC_CANBOTHUCHIEN CBTH ON CBTH.CanBoThucHienID = DKDT.ChuNhiemDeTaiID
		INNER JOIN THUCHIENDETAI_KIEMTRAGIAMSAT KT ON KT.DeTaiID = DKDT.DeTaiID
		LEFT JOIN THUCHIENDETAI_KIEMTRAGIAMSAT_CHITIET CT ON CT.KiemTraGiamSatID = KT.KiemTraGiamSatID
		WHERE (CBTH.CanBoThucHienID = @chuNhiemDeTai OR @chuNhiemDeTai IS NULL)
		AND (UPPER(LTRIM(RTRIM(DKDT.MaDeTai))) LIKE '%'+UPPER(LTRIM(RTRIM(@maDeTai)))+'%' OR @maDeTai IS NULL)  	
		AND (UPPER(LTRIM(RTRIM(DKDT.CoQuanChuTri))) LIKE '%' +UPPER(LTRIM(RTRIM(@coQuanChuTri)))+ '%' OR @coQuanChuTri IS NULL)
		AND (CT.NgayKiemTra = @ngayKiemTra OR @ngayKiemTra IS NULL)
	END
END
