--------BANG 6 BAO CAO DINH KY
CREATE PROC proc_PrintBang6_BCDK
	@IDBaoCaoDK INT
AS
	SELECT *,CONVERT(NVARCHAR(50),B.ThoiGianSuDung,103) AS pThoiGian 
	FROM(SELECT * FROM BANG6 NOLOCK WHERE BaoCaoDinhKyID=@IDBaoCaoDK) AS A
	LEFT JOIN(SELECT * FROM CHITIETBANG6 NOLOCK)AS B ON B.Bang6ID=A.Bang6ID
GO