--------BANG 1 BAO CAO DINH KY
CREATE PROC proc_PrintBang1_BCDK
	@IDBaoCaoDK INT
AS
SELECT A.*,B.TenDonViDo FROM(
	SELECT * FROM BANG1 NOLOCK WHERE BaoCaoDinhKyID=@IDBaoCaoDK
	) AS A
LEFT JOIN(SELECT * FROM DM_DONVIDO NOLOCK)AS B ON B.DMDonViDoID=A.DonViDoID