--------BANG 5 BAO CAO DINH KY
CREATE PROC proc_PrintBang5_BCDK
	@IDBaoCaoDK INT
as
	SELECT 
		a.*,B.Dot,B.SoTien
		,CONVERT(NVARCHAR(50),B.ThoiGian,103) AS pThoiGian
		 FROM(SELECT * FROM BANG5 NOLOCK WHERE BaoCaoDinhKyID=@IDBaoCaoDK) AS A
	LEFT JOIN(SELECT * FROM CHITIETBANG5 NOLOCK)AS B ON B.Bang5ID=A.Bang5ID