CREATE TABLE XETDUYETDETAI_TUYENCHONCAPQUANLY
(
	TuyenChonCapQuanLyID int NOT NULL IDENTITY,
	DeTaiID int NULL,--ref DANGKYDETAI
	GhiChu nvarchar(1000) NULL,
	CONSTRAINT FK_XETDUYETDETAI_TUYENCHONCAPQUANLY_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_XETDUYETDETAI_TUYENCHONCAPQUANLY_DeTaiID ON XETDUYETDETAI_TUYENCHONCAPQUANLY
( 
	DeTaiID         ASC
)
go