CREATE TABLE XETDUYETDETAI_BOSUNGSUADOI
(
	BoSungSuaDoiID int NOT NULL IDENTITY,
	LoaiVanBanChinhSuaBoSung nvarchar(1000) NULL,
	NgayChinhSuaBoSung date NULL,
	DeTaiID int NULL,--ref DANGKYDETAI
	CONSTRAINT PK_XETDUYETDETAI_BOSUNGSUADOI_BoSungSuaDoiID PRIMARY KEY CLUSTERED (BoSungSuaDoiID ASC),
	CONSTRAINT FK_XETDUYETDETAI_BOSUNGSUADOI_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_XETDUYETDETAI_BOSUNGSUADOI_DeTaiID ON XETDUYETDETAI_BOSUNGSUADOI
( 
	DeTaiID         ASC
)
go
