CREATE TABLE XETDUYETDETAI_GHINHANKETQUA
(
	GhiNhanKetQuaID int NOT NULL IDENTITY,
	DeTaiID int NULL,--ref HOIDONGDAODUC=> where DeTaiID = DeTaiID select KetQuaXetDuyet
	KinhPhiCapQuanLy money NULL,
	ThoiGianThucHienCapQuanLy date NULL,
	CONSTRAINT PK_XETDUYETDETAI_GHINHANKETQUA_GhiNhanKetQuaID PRIMARY KEY CLUSTERED (GhiNhanKetQuaID ASC),
	CONSTRAINT FK_XETDUYETDETAI_GHINHANKETQUA_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_XETDUYETDETAI_GHINHANKETQUA_DeTaiID ON XETDUYETDETAI_GHINHANKETQUA
( 
	DeTaiID         ASC
)
go