CREATE TABLE XETDUYETDETAI_DANGKYCAPQUANLY
(
	DangKyCapQuanLyID int NOT NULL IDENTITY,
	DeTaiID int NULL,--ref DANGKYDETAI
	GhiChu nvarchar(1000) NULL,
	CONSTRAINT PK_XETDUYETDETAI_DANGKYCAPQUANLY_DangKyCapQuanLyID PRIMARY KEY CLUSTERED (DangKyCapQuanLyID ASC),
	CONSTRAINT FK_XETDUYETDETAI_DANGKYCAPQUANLY_DeTaiID FOREIGN KEY (DeTaiID) REFERENCES DANGKYDETAI(DeTaiID)
)
GO

CREATE NONCLUSTERED INDEX IX_XETDUYETDETAI_DANGKYCAPQUANLY_DeTaiID ON XETDUYETDETAI_DANGKYCAPQUANLY
( 
	DeTaiID         ASC
)
go